apiVersion: apps/v1
kind: Deployment
metadata: 
  name: nginxreplicas
  # these labels are for replica set
  labels:
    project: headless-svc-demo
    purpose: replicas 
spec:
  replicas: 3
  selector: 
  # these labels are used to select pods
    matchLabels: 
      project: headless-svc-demo
      purpose: replicas 
    # pod definition
  template:
    metadata:
      labels:
        project: headless-svc-demo
        purpose: replicas 
    spec: 
      containers: 
      - name: nginx
        image: nginx
---
apiVersion: v1
kind: Service
metadata: 
  name: nginx-headless
spec: 
# If a service has cluster IP then it is called headless service
  clusterIP: None
  selector:
    project: headless-svc-demo
    purpose: replicas 
  ports:
    - protocol: TCP
      port: 80 #service port
      targetPort: 80 #container port